export const cars = [
  {
    id: "1",
    title: "Economy",
    multiplier: 2,
    image: require("@/assets/images/car1.png"),
  },
  {
    id: "2",
    title: "Comfort",
    multiplier: 4,
    image: require("@/assets/images/car2.png"),
  },
  {
    id: "3",
    title: "Premium",
    multiplier: 8,
    image: require("@/assets/images/car3.png"),
  },
];
export const drivers = [
  {
    id: "101",
    name: "Ahmed Hassan",
    rating: 4.9,
    carModel: "Toyota Corolla",
    plateNumber: "ABC-123",
    lat: 31.2156,
    lng: 29.9553,
    isAvailable: true,
    rideType: "Economy",
  },
  {
    id: "102",
    name: "Mohamed Ali",
    rating: 4.8,
    carModel: "Hyundai Elantra",
    plateNumber: "XYZ-456",
    lat: 31.205,
    lng: 29.92,
    isAvailable: true,
    rideType: "Economy",
  },
  {
    id: "103",
    name: "Omar Khaled",
    rating: 4.7,
    carModel: "Kia Cerato",
    plateNumber: "KIA-789",
    lat: 31.223,
    lng: 29.948,
    isAvailable: true,
    rideType: "Comfort",
  },
  {
    id: "104",
    name: "Youssef Adel",
    rating: 4.9,
    carModel: "Nissan Sunny",
    plateNumber: "SUN-321",
    lat: 31.211,
    lng: 29.961,
    isAvailable: true,
    rideType: "Economy",
  },
  {
    id: "105",
    name: "Karim Mostafa",
    rating: 4.6,
    carModel: "Chevrolet Optra",
    plateNumber: "OPT-654",
    lat: 31.208,
    lng: 29.943,
    isAvailable: false,
    rideType: "Economy",
  },
  {
    id: "106",
    name: "Mahmoud Samir",
    rating: 4.8,
    carModel: "Honda Civic",
    plateNumber: "HON-852",
    lat: 31.217,
    lng: 29.957,
    isAvailable: true,
    rideType: "Comfort",
  },
  {
    id: "107",
    name: "Tarek Ibrahim",
    rating: 5.0,
    carModel: "Toyota Camry",
    plateNumber: "CAM-963",
    lat: 31.219,
    lng: 29.95,
    isAvailable: true,
    rideType: "Premium",
  },
  {
    id: "108",
    name: "Hossam Nabil",
    rating: 4.5,
    carModel: "Hyundai Accent",
    plateNumber: "ACC-741",
    lat: 31.202,
    lng: 29.935,
    isAvailable: true,
    rideType: "Economy",
  },
];